version: '3'
services:
  web-fe:
    build: .
    command: python app.py
    ports:
      - "5001:5000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
